### ISSUE TITLE
NetStandart 1.6 ### XAMARIN FORMS ### FODY 2.2.11

### ISSUE THREAD

**Issue by dashika** [kswoll/ReactiveUI.Fody#56]
Help me, please, what I must do for deciding this problem:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Value cannot be null.
Parameter name: self
StackTrace:
   at Mono.Cecil.Rocks.TypeDefinitionRocks.GetConstructors(TypeDefinition self)
   at ReactiveUI.Fody.ObservableAsPropertyWeaver.Execute() in C:\projects\reactiveui-fody-ionu7\ReactiveUI.Fody\ObservableAsPropertyWeaver.cs:line 40
   at ReactiveUI.Fody.ModuleWeaver.Execute() in C:\projects\reactiveui-fody-ionu7\ReactiveUI.Fody\ModuleWeaver.cs:line 31
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 180
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 85
Source:
Mono.Cecil.Rocks
TargetSite:
System.Collections.Generic.IEnumerable`1[Mono.Cecil.MethodDefinition] GetConstructors(Mono.Cecil.TypeDefinition)
	CMTKXamarinForms		1

**Comment by dashika** [comment]
I found this : https://github.com/reactiveui/ReactiveUI/pull/1578/commits/d2ecf023642003dadfa031e466d0608e93378b56

but how it implement without built new own lib ?

**Comment by gtbuchanan** [comment]
Duplicate of #26 and #53. See #54 as there is a package attached to it that resolves this issue.
