### ISSUE TITLE
exception when building on a project that has no [Reactive] (or any) attributes defined.

### ISSUE THREAD

**Issue by ghuntley** [kswoll/ReactiveUI.Fody#9]
# Repro

```
File -> New Project (PCL 111)
PM> Install-Package ReactiveUI
PM> Install-Package Fody
PM> Install-Package ReactiveUI.Fody
```

Compile.
# Error

```
Severity    Code    Description Project File    Suppression State   Line
Error       Fody: An unhandled exception occurred:
Exception:
Could not find assembly: ReactiveUI.Fody.Helpers (System.Runtime, System.Resources.ResourceManager, Splat, ReactiveUI, System.Diagnostics.Debug, System.Collections, Akavache, System.Linq.Expressions, System.Threading.Tasks, System.Reactive.Core, System.Reactive.Linq, SimpleFeedReader, Akavache.Sqlite3, System.Reactive.Interfaces, System.Reflection, Conditions, System.ObjectModel)
StackTrace:
at ReactiveUI.Fody.ReactiveUIPropertyWeaver.Execute() in c:\projects\reactiveui-fody\ReactiveUI.Fody\ReactiveUIPropertyWeaver.cs:line 36
at ReactiveUI.Fody.ModuleWeaver.Execute() in c:\projects\reactiveui-fody\ReactiveUI.Fody\ModuleWeaver.cs:line 24
at lambda_method(Closure , Object )
at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 161
at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
ReactiveUI.Fody
TargetSite:
Void Execute()  ReactiveReader.Core         
```

**Comment by kswoll** [comment]
Fixed in ReactiveUI.Fody.1.1.10.nupkg
